[database]
path = "path/to/database"
cache = "path/to/cache"
price_db_path = "path/to/price_db"

[search]
out_degree_limit = 1000
depth = 10

[flow]
activate_threshold = 100
age_limit = 10
label_limit = 3000

[log]
level = "info"