[database]
path = "path/to/database"
cache = "path/to/cache"
price_db_path = "path/to/price_db"

[search]
out_degree_limit = 5000
depth = 20

[flow]
activate_threshold = 100
age_limit = 20
label_limit = 1000

[log]
level = "info"